### PR TITLE
Early reestablish

### LINKED ISSUE #19: info callbacks have incorrect round and incorrect initiator
https://github.com/aeternity/ae-channel-service/blob/8b82f7e9c63a9a099e9e78a55dbc9eacbe6ef02e/apps/ae_socket_connector/test/scenarios_test.exs#L15
`{:initiator, %{message: {:channels_info, 0, :transient, "own_funding_locked"}}}`

Solution could be to remove the incorrect info alternatively make sure it produces same information as channels_update
`{:responder, %{message: {:channels_update, 1, :transient, "channels.update"}}}`

### LINKED ISSUE #57: Don't use macros for urls and node names
Requires full recompile on change, this non intuitive,

### PR DESCRIPTION
**Pull request by AleksandarFilipov**
This code is dependent on https://github.com/aeternity/aeternity/issues/3169
Protocol updates https://github.com/aeternity/protocol/pull/470

Initiator can now leave and reestablish early as soon as channel_id is populated. More below.

This branch is the natural continuation for backend_service
* Channel_id (and fsm_id) is now picked up at `"funding_signed"` and "funding_created"` 
* Channel_id is populated automatically in the phoenix interface, allowing leave/reestablish without manually editing fields.
* Backend now supervises all channels
* Removed initiator and round when not available (channels_info and on_chain)
* Contact is automatically deployed at ":channels_info, round 1" 
* It's now ok to hit start backend channel multiple times (well only relevant after the channel id is present)
Closes #57 and closes #19

### CODE REVIEW

File: apps/ae_socket_connector/lib/session_holder.ex [hunk 1]
```diff
@@ -132,20 +132,20 @@ defmodule SessionHolder do
...
+      nil -> Logger.warn("Not persisting to disk, channel_id missing, role #{inspect socketconnector_state.role}")
       _ ->
         case :dets.insert(file_ref, {socketconnector_state.channel_id, dets_state}) do
           :ok ->
             case :dets.sync(file_ref) do
               :ok -> :ok
                 case socketconnector_state.fsm_id == nil do
                   true ->
-                    Logger.warn("Persisted data not satisfying reestablish requirements, fsm_id: #{inspect socketconnector_state.fsm_id} channel_id #{inspect socketconnector_state.channel_id}")
+                    Logger.warn("Persisted data not satisfing reestablish requirements, fsm_id: #{inspect socketconnector_state.fsm_id} channel_id #{inspect socketconnector_state.channel_id} role #{inspect socketconnector_state.role}")
```
Comment (Artur64) [inline apps/ae_socket_connector/lib/session_holder.ex]:
```suggestion
                    Logger.warn("Persisted data not satisfying reestablish requirements, fsm_id: #{inspect socketconnector_state.fsm_id} channel_id #{inspect socketconnector_state.channel_id} role #{inspect socketconnector_state.role}")
```

File: apps/ae_socket_connector/lib/session_holder.ex [hunk 2]
```diff
@@ -132,20 +132,20 @@ defmodule SessionHolder do
...
                   false ->
-                    Logger.info("Persisted data SATISFYING reestablish requirements, fsm_id: #{inspect socketconnector_state.fsm_id} channel_id #{inspect socketconnector_state.channel_id}")
+                    Logger.info("Persisted data SATISFING reestablish requirements, fsm_id: #{inspect socketconnector_state.fsm_id} channel_id #{inspect socketconnector_state.channel_id} role #{inspect socketconnector_state.role}")
```
Comment (Artur64) [inline apps/ae_socket_connector/lib/session_holder.ex]:
```suggestion
                    Logger.info("Persisted data SATISFYING reestablish requirements, fsm_id: #{inspect socketconnector_state.fsm_id} channel_id #{inspect socketconnector_state.channel_id} role #{inspect socketconnector_state.role}")
```

File: apps/ae_socket_connector/lib/socket_connector.ex [hunk 3]
```diff
@@ -1008,9 +1009,19 @@ defmodule SocketConnector do
     {poi, %__MODULE__{state | round_and_updates: Map.put(state.round_and_updates, round, update_new)}}
   end
 
+  # can be removed once this is fixed
```
Comment (Artur64) [inline apps/ae_socket_connector/lib/socket_connector.ex]: Should we make a separate issue for it, just not to forget to remove it?

**Review by Artur64 — APPROVED** [review]
Looks good to me overall! Few comments

File: apps/ae_socket_connector/lib/socket_connector.ex [hunk 4]
```diff
@@ -1008,9 +1009,19 @@ defmodule SocketConnector do
...
+  # https://github.com/aeternity/aeternity/issues/3186
+  def process_message(%{"channel_id" => _channel_id, "error" => %{"data" => %{"message" => "Invalid fsm id"}}} = error, state) do
```
Comment (AleksandarFilipov) [inline apps/ae_socket_connector/lib/socket_connector.ex]:
```suggestion
  def process_message(%{"channel_id" => _channel_id, "error" => %{"data" => [%{"message" => "Invalid fsm id"}]}} = error, state) do
```

File: apps/ae_socket_connector/lib/socket_connector.ex (hunk 3 above)
Comment (AleksandarFilipov) [reply apps/ae_socket_connector/lib/socket_connector.ex]: When i look at the code i think it should probably stay, i'll rephrase my comment.

Comment (AleksandarFilipov) [inline apps/ae_socket_connector/lib/socket_connector.ex]:
```suggestion
  # could possibly be removed once this is fixed
```
